I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 97, in script
    c "... Me sinto enjooada, "
Exception: Sayer 'c' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 97, in script
    c "... Me sinto enjooada, "
  File "C:\Users\aline\Documents\renpy-8.2.1-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "C:\Users\aline\Documents\renpy-8.2.1-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\aline\Documents\renpy-8.2.1-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'c' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.2.24050801+nightly
Stars Selection 1.0
Thu Jun 13 18:21:00 2024
